### ISSUE TITLE
Error: title is required

### ISSUE THREAD

**Issue by svandragt** [nixjdm/lektor-atom#6]
I'm posting tweets to my Lektor blog which don't have a title. This works fine but causes issues with lector-atom ValueError: title is required.

Reproduce: create a blog post without title and publish it.

So the atom spec says that entry titles are required. But in RSS2 they are optional. I'm importing micro posts (tweets for example) which do not have a title. Lektor is fine with this. The model content file contains a title field but with an empt value. Could you perhaps allow an empty string?

**Comment by goanpeca** [comment]
@svandragt is this still an issue?

**Comment by svandragt** [comment]
No idea ive not used lektor for over a year

**Comment by goanpeca** [comment]
@svandragt any reason you are no longer using lektor?

**Comment by svandragt** [comment]
I work with WordPress professionally now. Lektor is a good system :)

**Comment by svandragt** [comment]
This is no longer an issue, the title of the post is replaced with the title of the model (in my case Status Post) in the feed, which is great.
