### ISSUE TITLE
AttributeError: 'Page' object has no attribute 'id'

### ISSUE THREAD

**Issue by severen** [nixjdm/lektor-atom#9]
Occurs when building both my own website and @singingwolfboy's using both latest master checkout on Python 2 and 3 or the latest release on both Python 2 and 3.

**Comment by skorokithakis** [comment]
One of your fields is invalid.

**Comment by goanpeca** [comment]
Is this a valid issue?

**Comment by skorokithakis** [comment]
I'm sorry, I don't remember now, but I think I had run into the same error and discovered I had an invalid field.

**Comment by goanpeca** [comment]
@severen any chance of getting a reproducible example?

**Comment by severen** [comment]
I opened this issue so long ago that I honestly don't even remember what I used this project for. So no, probably not sorry :p

**Comment by eigengrau** [comment]
This seems to arise from a typo in the error reporting code (line 153) when a feed references a non-existing field, where it should be `_id`, not `id`. Additionally, it looks like when not within a templating context, one can only access record fields using `foo['_id']`, not via attribute access.
